from k8s.gcr.io/k8s-dns-sidecar:1.14.13
RUN wget -O /tmp/kubernetes-client-linux-amd64.tar.gz https://dl.k8s.io/v1.13.1/kubernetes-client-linux-amd64.tar.gz
RUN wget -O /tmp/kubernetes-server-linux-amd64.tar.gz https://dl.k8s.io/v1.13.1/kubernetes-server-linux-amd64.tar.gz
RUN wget -O /tmp/kubernetes-node-linux-amd64.tar.gz https://dl.k8s.io/v1.13.1/kubernetes-node-linux-amd64.tar.gz
RUN wget -O /tmp/etcd-v3.3.10-linux-amd64.tar.gz https://github.com/etcd-io/etcd/releases/download/v3.3.10/etcd-v3.3.10-linux-amd64.tar.gz
RUN wget -O /tmp/flannel-v0.10.0-linux-amd64.tar.gz https://github.com/coreos/flannel/releases/download/v0.10.0/flannel-v0.10.0-linux-amd64.tar.gz

RUN wget -O /tmp/cfssl-certinfo_linux-amd64 https://pkg.cfssl.org/R1.2/cfssl-certinfo_linux-amd64
RUN wget -O /tmp/cfssl_linux-amd64 https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
RUN wget -O /tmp/cfssljson_linux-amd64 https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64

MAINTAINER chinahyq
