from k8s.gcr.io/k8s-dns-sidecar:1.14.13
RUN wget -O /tmp/spark-3.0.0-preview2-bin-hadoop3.2.tgz http://apache.mirror.cdnetworks.com/spark/spark-3.0.0-preview2/spark-3.0.0-preview2-bin-hadoop3.2.tgz
MAINTAINER chinahyq
