from k8s.gcr.io/k8s-dns-sidecar:1.14.13
RUN wget -O /tmp/hadoop-3.2.1.tar.gz http://apache.mirror.cdnetworks.com/hadoop/common/stable/hadoop-3.2.1.tar.gz
RUN wget -O /tmp/apache-zookeeper-3.6.1-bin.tar.gz http://archive.apache.org/dist/zookeeper/zookeeper-3.6.1/apache-zookeeper-3.6.1-bin.tar.gz
RUN wget -O /tmp/hbase-2.2.4-bin.tar.gz http://apache.mirror.cdnetworks.com/hbase/2.2.4/hbase-2.2.4-bin.tar.gz
RUN wget -O /tmp/apache-hive-3.1.2-bin.tar.gz http://apache.mirror.cdnetworks.com/hive/hive-3.1.2/apache-hive-3.1.2-bin.tar.gz
RUN wget -O /tmp/spark-3.0.0-preview2-bin-hadoop3.2.tgz https://www.apache.org/dyn/closer.lua/spark/spark-3.0.0-preview2/spark-3.0.0-preview2-bin-hadoop3.2.tgz
RUN wget -O /tmp/kafka_2.11-2.4.1.tgz http://apache.mirror.cdnetworks.com/kafka/2.4.1/kafka_2.11-2.4.1.tgz
RUN wget -O /tmp/scala-2.11.12.tgz https://downloads.lightbend.com/scala/2.11.12/scala-2.11.12.tgz
MAINTAINER chinahyq
